### Word2Vec using Tensorflow

#### Introduction

Meaning of word is the representation or idea conveyed. Word embeddings are numerical representations of the words to make computers understand natural language. The idea is to have similar words or words used in similar context to be close to each other in higher dimension space.

But before we look at using word vectors, let us look at classical NLP approach, Wordnet.

##### Wordnet

- Wordnet is a lexical database encoding parts of speech and tags relationsships between words including nouns, adjectives, verbs and adverbs. 
- English Wordnet hosts over 150000 words and over 100000 synonym groups(synsets)
- Synset is a set of synonyms
- Each Synset has a definition which tells what the synset repesents
- Each Synonym in a Synset is called a Lemma.
- Synsets form a graph and are associated with another synset with a specific type of relationship
- Following are the relationship types
    - Hypernym of a synset carry a general, high level meaning of a considered synset. For e.g. Vehicle is a hypernym of synset car. It forms `is-a` relation
    - Hyponym of a synset carry a more specific meaning of a synset. Toyota Car is a Hyponym of a car. It forms `is-a` relation
    - Holonym are synsets that make up the whole entity of the considered synset. If is a `made-of` relation. For example, Tyre has a holonym cars.
    - Meronym are opposite of Holonym, they form a `is-made-of` relation.
    
Let us look at wordnet in action from nltk

In [1]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/amolnayak/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [2]:
from nltk.corpus import wordnet as wn

word = 'car'
car_syns = wn.synsets(word)

synset_defs = [car_syn.definition() for car_syn in car_syns]
print('Synset definitions for word', word, 'are\n\n','\n\n- '.join(synset_defs))

Synset definitions for word car are

 a motor vehicle with four wheels; usually propelled by an internal combustion engine

- a wheeled vehicle adapted to the rails of railroad

- the compartment that is suspended from an airship and that carries personnel and the cargo and the power plant

- where passengers ride up and down

- a conveyance for passengers or freight on a cable railway


Let us get the hypernym and holonym of first synset of the cars we got

In [3]:
car_syn = car_syns[0]

hypernyms = car_syn.hypernyms()
hypernym_list = '\n\t '.join(['\n\t '.join(h.lemma_names()) for h in hypernyms])
print('Hypernym of synset containing car are,\n\t', hypernym_list)

hyponyms = car_syn.hyponyms()
hyponyms_list = '\n\t '.join(['\n\t '.join(h.lemma_names()) for h in hyponyms])
print('\nHyponyms of synset containing car are,\n\t', hyponyms_list)


Hypernym of synset containing car are,
	 motor_vehicle
	 automotive_vehicle

Hyponyms of synset containing car are,
	 ambulance
	 beach_wagon
	 station_wagon
	 wagon
	 estate_car
	 beach_waggon
	 station_waggon
	 waggon
	 bus
	 jalopy
	 heap
	 cab
	 hack
	 taxi
	 taxicab
	 compact
	 compact_car
	 convertible
	 coupe
	 cruiser
	 police_cruiser
	 patrol_car
	 police_car
	 prowl_car
	 squad_car
	 electric
	 electric_automobile
	 electric_car
	 gas_guzzler
	 hardtop
	 hatchback
	 horseless_carriage
	 hot_rod
	 hot-rod
	 jeep
	 landrover
	 limousine
	 limo
	 loaner
	 minicar
	 minivan
	 Model_T
	 pace_car
	 racer
	 race_car
	 racing_car
	 roadster
	 runabout
	 two-seater
	 sedan
	 saloon
	 sport_utility
	 sport_utility_vehicle
	 S.U.V.
	 SUV
	 sports_car
	 sport_car
	 Stanley_Steamer
	 stock_car
	 subcompact
	 subcompact_car
	 touring_car
	 phaeton
	 tourer
	 used-car
	 secondhand_car


As we see above, hypernyms are more general than the word `car` and the hyponyms are specyfic types of cars (most of them).

Let us look at Holonyms and Meronyms

In [4]:
holonyms = car_syn.part_holonyms()
holonyms = '\n\t '.join(['\n\t '.join(h.lemma_names()) for h in holonyms])
if len(holonyms):
    print('Holonyms are\n\t', holonyms)
else:
    print('No Holonyms found')

meronyms = '\n\t '.join(['\n\t '.join(m.lemma_names()) for m in car_syn.part_meronyms()])
if len(meronyms):
    print('Meronyms are\n\t', meronyms)
else:
    print('No Meronyms found')

No Holonyms found
Meronyms are
	 accelerator
	 accelerator_pedal
	 gas_pedal
	 gas
	 throttle
	 gun
	 air_bag
	 auto_accessory
	 automobile_engine
	 automobile_horn
	 car_horn
	 motor_horn
	 horn
	 hooter
	 buffer
	 fender
	 bumper
	 car_door
	 car_mirror
	 car_seat
	 car_window
	 fender
	 wing
	 first_gear
	 first
	 low_gear
	 low
	 floorboard
	 gasoline_engine
	 petrol_engine
	 glove_compartment
	 grille
	 radiator_grille
	 high_gear
	 high
	 hood
	 bonnet
	 cowl
	 cowling
	 luggage_compartment
	 automobile_trunk
	 trunk
	 rear_window
	 reverse
	 reverse_gear
	 roof
	 running_board
	 stabilizer_bar
	 anti-sway_bar
	 sunroof
	 sunshine-roof
	 tail_fin
	 tailfin
	 fin
	 third_gear
	 third
	 window


As we see above, there are no holonyms of car but a car is composed of a lot of parts and thus we have found a lot of meronyms. 

If we choose a word from the above meronyms and find its holonyms, we should find car in it as seen below

In [5]:
car_part = 'sunroof'
first_synset = wn.synsets(car_part)[0]

carpart_holonyms = '\n\t '.join(['\n\t '.join(h.lemma_names()) for h in first_synset.part_holonyms()])
print('Holonyms of', car_part, 'are\n\t', carpart_holonyms)

carpart_meronyms = '\n\t '.join(['\n\t '.join(h.lemma_names()) for h in first_synset.part_meronyms()])
if len(carpart_meronyms):
    print('Meronyms of', car_part, 'are\n\t', carpart_meronyms)
else:
    print('No meronyms for', car_part, 'found')

Holonyms of sunroof are
	 car
	 auto
	 automobile
	 machine
	 motorcar
No meronyms for sunroof found


We will now find similarities between the synsets. (TODO, get more info on similarity metrics). We will use Wu-Palmer similarity to find similarity between all pairs of ``car_syns``



In [6]:
import numpy as np
car_lemmas = '\n\t '.join([', '.join(s.lemma_names()) for s in car_syns])
print('\nLemmas in all the synsets are\n\t', car_lemmas)
sim_mat = np.matrix([[wn.wup_similarity(syn1, syn2) for syn1 in car_syns] for syn2 in car_syns])
print('\nWu-Palmer similarity matrix constructed is\n', sim_mat)



Lemmas in all the synsets are
	 car, auto, automobile, machine, motorcar
	 car, railcar, railway_car, railroad_car
	 car, gondola
	 car, elevator_car
	 cable_car, car

Wu-Palmer similarity matrix constructed is
 [[ 1.          0.72727273  0.47619048  0.47619048  0.47619048]
 [ 0.72727273  1.          0.52631579  0.52631579  0.52631579]
 [ 0.47619048  0.52631579  1.          0.9         0.9       ]
 [ 0.47619048  0.52631579  0.9         1.          0.9       ]
 [ 0.47619048  0.52631579  0.9         0.9         1.        ]]


##### Problems with Wordnet

- Misses the nuances of two entities. For example, `want` and `need` have similar meanings with `need` being more assertive
- It is subjective as the corpus is created and maintained by a small community
- Labor intensive in maintaining Wordnet
- Developing Wordnet for other languages is costly


#### Vector Reprsentation of words

##### One Hot Encoding

Consider we have a vocubulary of size V, then each word will be repesented with a vector of size V with the element representing that word in the vocabulary set to 1 and everything else 0.
The problem with this approach are 
- It cannot capture context and similarity between similar words is 0. 
- The size of vectors become huge as the size of Vocubalary increases.


##### TF-IDF

It measures the importance of a word in the document. A more frequently occurring word is not necessarily the an important word in the document. TF-IDF takes of this as follows

- Term Frequency (TF): The count of a term in the corpus. This term possibly gives more frequently occurring words like `and`, `a`, `the` etc more weight. Formally $TF(w_i, doc)$ = count of $w_i$ in doc / number of words in doc
    
- Inverse Document frequency (IDF): This term downweights words which are frequent across the corpus. This operation will downweight these words like `and`, `a`, `the` etc. 
$IDF(w_i)$ = $log$(number of documents / number of documents with word $w_i$)


For example, suppose we have the following two sentences (each in its own document) in the corpus

- Document 1: This is about cats. Cats are great companions
- Document 2: This is about dogs. Dogs are very loyal



For document 1,

TF-IDF(cats, doc1) = (2 / 8) * log(2/ 1) = 0.075
 
TF-IDF(this, doc1) = (1 / 8) * log(2/ 2) = 0


##### Co-occurance Matrix

Co-occurance matrix captures the cooccurance of words. If a vocabulary is of size V, the co-occurance matrix is of size $V \times V$. Unline one hot encoded vectors, we keep a track of the context of the words. The matrix is symmetric across diagonals and only a half of it is enough to convey information.

Consider the following two sentences

*Jerry and Mary are friends*

*Jerry buys flowers for Mary*

Following code is an example of building cooccurance matrix. 

In [7]:
import itertools
import numpy as np

corpus = ['Jerry and Mary are friends', 'Jerry buys flowers for Mary']

def get_neighbors(sentence, center_word_index):
    #Sentence as splits of words
    if center_word_index == 0:
        return [sentence[1]]
    elif center_word_index == len(sentence) - 1:
        return [sentence[center_word_index - 1]]
    else:
        return [sentence[center_word_index - 1], sentence[center_word_index + 1]]

split_tokens_sample = corpus[0].lower().split(' ')
print('\nTesting get_neighbors for', split_tokens_sample)
print('\tget_neighbors(corpus_split_tokens[0], 0) gives', get_neighbors(split_tokens_sample, 0))
print('\tget_neighbors(corpus_split_tokens[0], 4) gives', get_neighbors(split_tokens_sample, 4))
print('\tget_neighbors(corpus_split_tokens[0], 2) gives', get_neighbors(split_tokens_sample, 2))

def compute_coccurance(corpus):
    corpus_split_tokens = [s.lower().split(' ') for s in corpus]
    vocabulary = list(set(itertools.chain.from_iterable(corpus_split_tokens)))
    print('Vocabulary is', vocabulary)

    co_matrix = np.zeros((len(vocabulary), len(vocabulary)))
    
    for split_sentence in corpus_split_tokens:
        for center_word in range(len(split_sentence)):
            neighbors = get_neighbors(split_sentence, center_word)
            cent_word_vocab_index = vocabulary.index(split_sentence[center_word])
            for neighbor in neighbors:
                neighbor_word_vocab_index = vocabulary.index(neighbor)
                co_matrix[cent_word_vocab_index, neighbor_word_vocab_index] += 1
                
    return co_matrix

print()
co_matrix = compute_coccurance(corpus)
print('Coccurance Matrix is\n', co_matrix)


Testing get_neighbors for ['jerry', 'and', 'mary', 'are', 'friends']
	get_neighbors(corpus_split_tokens[0], 0) gives ['and']
	get_neighbors(corpus_split_tokens[0], 4) gives ['are']
	get_neighbors(corpus_split_tokens[0], 2) gives ['and', 'are']

Vocabulary is ['flowers', 'for', 'jerry', 'are', 'and', 'friends', 'buys', 'mary']
Coccurance Matrix is
 [[ 0.  1.  0.  0.  0.  0.  1.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  1.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  1.]
 [ 0.  0.  1.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  1.  1.  0.  0.  0.]]



We can see the problem with this approach

- Increase in size of vocabulary increases the size of the matrix polynomially
- Context windows larger than 1 will result increased complexity of maintaining cooccurance count. One approach will be to weight down words further from the center word.


##### Introducing Word2Vec

Word2Vec is a distributed word representation learning technique. It has the following advantages

- Its representation is not subjective like Wordnet
- It doesn't lose context like one hot vector representation does
- It's vector size doesn't depend on the size of the vocabulary unlike one hot encoding or cooccurance matrix.

The essence of Word2Vec is to capture the context of the word by looking at the surrounding words. Context means the a finite number of words before and after the center word of interest.

Mathematically, the following probability should be high given the center word i.

$P(w_{i - m},... w_{i - 1}, w_{i + 1}, ...w_{i + m} \vert w_i)\: = \: \prod_{j = i - m \wedge j \ne i}^{i + m} P(w_j \vert w_i) $


###### Designing the Loss function for learning word embedding

We see the above probability if what we try to maximize. To a neural network the loss function $J(\theta)$ will thus minimize the negative of the above probability.

Suppose

- N: is the number of words (tokens) in the sentence
- m: Window size, that is take m words to the left and m words to the right of the center word

The loss function thus will be

$J(\theta)\: = \: -\frac{1}{N - 2m}\sum_{i = m + 1}^{N - m}\prod_{j = i - m \wedge j \ne i}^{i + m} P(w_j \vert w_i)$

To break it down, we have $\frac{1}{N - 2m}$ in the term because for a string of length N, we have to start with the $m + 1^{th}$ word and go no more than $N - m^{th}$ word. Thus giving is N - 2m different probabilities. The summation precisly adds up all these probabilities values amnd dividing by the possible values gives the mean.
Since the probability is to be maximized and in general while optimizing the weights of a neural network we minimize, we add the negative sign.

We dont want to deal with the product in our loss function and thus we take log of the probabilities which converts these products to sum of log probability, thus our loss function becomes

$J(\theta)\: = \: -\frac{1}{N - 2m}\sum_{i = m + 1}^{N - m}\sum_{j = i - m \wedge j \ne i}^{i + m} log(P(w_j \vert w_i))$

This formulation is called ***Negative log likelyhood***


#### The Skipgram Algorithm

##### Data preparation
The first task would be to prepare the input data. Following approach will be used for preparing the input data

- For a given word $w_i$ and window size m, the context window including the target word will be of size 2m + 1
- If $w_i$ if the current target word, the tuples generated will be [($w_i$, $w_{i - m}$), ...($w_i$, $w_{i - 1}$), ($w_i$, $w_{i + 1}$), ...($w_i$, $w_{i + m}$)]

For example, if the sentence is *The dog barked at the mailman*, with window size 1, we will have the following tuples

*[(dog, The), (dog, barked), (barked, dog), (barked, at), ..., (the, at), (them mailman)]*

These tuples actually are the input and the expected output.

##### Network Design

- Let the Vocubalary be of size V and our embedding be of dimension D
- The embedding layer is of size $V \times D$, lets call these matrix E
- From our input pair *(target, context)*, create a one hot encoded vector of the context word and target word of dimension V. We will call these one hot encoded vectors $x_i$ and $y_i$ respectively
- Lookup the embedding for the context word ($x_i$) by doing $x_i \cdot E$. Since $x_i$ has dimension $1 \times V$ and E has dimension $V \times D$, the dot product gives us a vector of size $1 \times D$, which is the word embedding corresponding to the input context word, let call this embedding vector correponding to the context word, $z_i$
- We next find the $logit(x_i)\:=\:z_i \cdot W + b$ where W is the weight matrix of dimension $D \times V$ and b is the bias vector of dimension $V \times 1$. The output are logits of dimension $1 \times V$
- We then use softmax layer to generate our prediction $\hat{y_i}$ where $\hat{y_i}\:=\:softmax(logit(x_i))$
- Since we know the context $y_i$, we can back propagate the loss and update the weights and embeddings.


The original skipgram model uses two distinct embeddings of dimension $V \times D$ to represent the word as context and when it is a target word.

##### Loss Function

We saw earlier that the loss function to use is 

$J(\theta)\:=\:-\frac{1}{N - 2m}\sum_{i = m + 1}^{N - m} \sum_{j = i-m \wedge i \ne j}^{i + m} log(P(w_j \vert w_i))$

However, based on the data we have it is not straightforward how to use this loss function


We will first look at $P(w_j \vert w_i)$, 

$w_i$ is a context word of the $n^{th}$ observation and represented as a one hot encoded vector of dimension V, $x_n$. Similarly, $w_j$ is our target vector and represented as one hot encoded vector $y_n$.

$P(w_j \vert w_i)\:=\: \frac{exp(logit(x_i)_{w_j})}{\sum_{k = 1}^v exp(logit(x_i)_{w_k})}$ 

$logit(x_i)$ are the raw outputs of dimension V generated by the neural network.
The numerator of the above term corresponds to the logit scalar value corresponding to the index of word $w_j$ (the index of the none zero value in the one hot encoded vector $y_n$).

For example, consider the sentence *I love NLP* and these three are the only words in our vocabulary.

Now we have two inputs for context word love, *(love, I)* and *(love, NLP)*

Assume that the one-hot encoded vectors are as follows

love -> [1, 0, 0]

I -> [0, 1, 0]

NLP -> [0, 0, 1]

and the logits when the word love given as input are [2, 10, 5], then following are the probabilities

$P(love \vert love)$ = exp(2) / exp(2) + exp(10) + exp(5) = 0.0003

$P(I \vert love)$ = exp(10) / exp(2) + exp(10) + exp(5) = 0.9930

$P(NLP \vert love)$ = exp(5) / exp(2) + exp(10) + exp(5) = 0.0067


Coming back to the cost function, we saw

$P(w_j \vert w_i)\:=\: \frac{exp(logit(x_i)_{w_j})}{\sum_{k = 1}^v exp(logit(x_i)_{w_k})}$ 

therefore

$log(P(w_j \vert w_i))\:=\: logit(x_i)_{w_j} - log ({\sum_{k = 1}^v exp(logit(x_i)_{w_k})})$ 

The cost function now becomes

$J(\theta)\:=\:-\frac{1}{N - 2m}\sum_{i = m + 1}^{N - m} \sum_{j = i-m \wedge i \ne j}^{i + m} logit(x_i)_{w_j} - log ({\sum_{k = 1}^v exp(logit(x_i)_{w_k})})$


Continuing with the above example with sentence *I love NLP*, the loss when love is the center word is as follows

$logit(x_i)_{w_j}$ = 10

log ({\sum_{k = 1}^v exp(logit(x_i)_{w_k})}) = log(exp(2) + exp(10) + exp(5)) = log(22182.26801) = 10.007


Therefore the loss is -(10 - 10.007) = 0.007 (log is natural log)


The cost function still is not practical as computing the loss for a single example will require us to calulate the logits for the entire vocabulary with the current context word. This can be seen from the $log ({\sum_{k = 1}^v exp(logit(x_i)_{w_k})})$ in the loss function

We therefore need a good approximation of an error function that is efficient.

---

The above formulation is right on paper, but we need a different approximation for the loss funntion used for training the network. The first approach we will look at is taking the **Negative Sampling** technique

Softmax at the output layer for a vocabulary of size V is a multinomial classification with V possible classes. We do not want a proper probability of a context word given the target word but given a pair of words we should be able to classify whether it is a context word or noise for the given target word. We therefore convert this multinomial classification problem to a binomial classification problem. Refer to [this](https://arxiv.org/pdf/1410.8251.pdf) url for notes on NCE (**Noise Contrastive Estimation**)

In negative sampling, let $p(D = 1 \vert w, c)$ denote the probability that the pair (w, c) came from our training data, that is, this sample is a true target context word pair. Therefore $p(D = 0 \vert w, c) = 1-  p(D = 0 \vert w, c)$ is the probabilility that the pair (w, c) didn't come from training sample, that is it is a negative sample.

The new goal therefore now given we are looking to train a binomial classifier detecting whether the given (w, c) pair is a target context word pair and our new objective is

$argmax_{\theta}\prod_{(w, c) \in D} p(D = 1\vert w, c ;\theta)$

Taking log probability we have the following objective to maximise

$argmax_{\theta}\sum_{(w, c) \in D} log(p(D = 1\vert w, c ;\theta))$

with the word embedding $v \in R^d$ we can use a sigmoid function to predict 

$p(D = 1\vert w, c; \theta) = \frac{1}{1 + e^{-v^t.v^w}} = \sigma(v^t.v^w)$

Therefore the new objective to minimize will be  

$argmax_{\theta}\sum_{(w, c) \in D} log(\frac{1}{1 + e^{-v^t.v^w}})$

This is trivial to solve as of the term $v^t.v^w$ is large, then we have the probability set to 1 and thus log probability will be 0. This thus will push all the word vector dot products to a high scalar value not achieving anything.

To make the network differentiate these true samples from negative samples, we introduce some negative samples to the training.

Thus we now change the objective function to accomodate these negative samples making our new objective to minimize 

$argmax_{\theta}\prod_{(w, c) \in D} p(D = 1\vert w, c ;\theta) \prod_{(w, c) \in D^{\prime}} p(D = 0\vert w, c ;\theta)$

= $argmax_{\theta}\prod_{(w, c) \in D} p(D = 1\vert w, c ;\theta) \prod_{(w, c) \in D^{\prime}} 1 - p(D = 1\vert w, c ;\theta)$

= $argmax_{\theta}\sum_{(w, c) \in D} log(p(D = 1\vert w, c ;\theta)) + \sum_{(w, c) \in D^{\prime}} log(1 - p(D = 1\vert w, c ;\theta))$

Since we know

$p(D = 1\vert w, c; \theta) =  \sigma(v^t.v^w)$

The function to minimize is 

= $argmax_{\theta}\sum_{(w, c) \in D} log(\sigma(v^t.v^w)) + \sum_{(w, c) \in D^{\prime}} log(1 - \sigma(v^t.v^w))$

= $argmax_{\theta}\sum_{(w, c) \in D} log(\sigma(v^t.v^w)) + \sum_{(w, c) \in D^{\prime}} log(\sigma(-v^t.v^w))$
 
as $\sigma(1 - x) = \sigma(-x)$


One question remains for us to answer is how do we get $D^\prime$ and how many negative samples (k) per positive sample do we add. The paper states k = 2 to 5 for large corpus and around 5 to 20 for small corpus.

For selecting the negative sample, the sample is chosen from a unigram distribution with the probability of a word being selected is given by 

$p(w_i) = \frac{f(w_i)^{3/4}}{\sum_{j = 0}^{n}f(w_j)^{3/4}}$

where $f(w_i)$ is the frequency of the word i in the corpus. More the count of this word, more is the probability of it being sampled. The power 3/4 is emperical and has no mathematical proof and it appears to have outperformed other function for the negative word sampling.

Note: The paper at [this](https://arxiv.org/pdf/1402.3722v1.pdf) URL was helpful in understanding the negative sampling formulation. Also [this](http://mccormickml.com/2016/04/19/word2vec-tutorial-the-skip-gram-model/) post is pretty useful and a good read

---

##### Hierarchical Softmax.

The original probability $p(w_i|w_j)= \frac{exp(logit(x_i)_{w_j})}{\sum_{k = 1}^v exp(logit(x_i)_{w_k})}$ where $x_i$ is the one hot encoded vector of the target word. The computationally demanding part of this equation is the denominator which gets huge for large vocabulary and increases linearly with vocabulary size. Hierarchical softmax addressed this problem and brings this complexity from linear to logarithamic. Unlike Negative sampling hierarchical softmax doesn't require fake negative samples and only uses the true (target, context) pair.

TODO: See this in more details with math and a real implementation.

---

We will implement skipgram using tensorflow, First, download the zip file corpus


In [8]:
from urllib.request import urlretrieve
import os
import shutil

def maybe_download(url, filename):
    if os.path.exists(filename):
        print('File %s already downloaded, using local copy'%filename)
    else:
        #Not handling exceptions and missing file errors
        print('Downloading file %s from %s'%(filename, url))
        local_filename, headers = urlretrieve(url + '/' + filename)
        shutil.move(local_filename, filename)
    
maybe_download('http://www.evanjones.ca/software','wikipedia2text-extracted.txt.bz2')

File wikipedia2text-extracted.txt.bz2 already downloaded, using local copy


Lets open and the corpus

In [9]:
import bz2
import nltk
import os
import math

#Read the data 1 MB bytes at a time
def read_corpus(archive):
    file_size = os.stat(archive).st_size
    chunk_size = 1024 * 1024
    tokens = []
    with bz2.open(archive) as f:
        for i in range(math.ceil(file_size // chunk_size) + 1):
            bytes_to_read = min(chunk_size, file_size - (i * chunk_size))
            file_str = f.read(bytes_to_read).decode('utf-8').lower()
            tokens.extend(nltk.word_tokenize(file_str))
        
    return tokens


content = read_corpus('./wikipedia2text-extracted.txt.bz2')

In [10]:
print('Number of tokens are ', len(content))
print('First 10 tokens are ', content[0:10])
print('Last 10 tokens are ', content[-10:])

Number of tokens are  3360286
First 10 tokens are  ['propaganda', 'is', 'a', 'concerted', 'set', 'of', 'messages', 'aimed', 'at', 'influencing']
Last 10 tokens are  ['favorable', 'long-term', 'outcomes', 'for', 'around', 'half', 'of', 'those', 'diagnosed', 'with']


We now create the following 4 data structures

- `dictionary`: Maps a string word to id creating a `(word, word_index)` pair.
- `reverse_dictionary`: Maps a word index to word pair as `(word_index, word)`
- `counts`: List of words and count pair as (word, num_occurance_of_word)
- `data`: List of same size as content, but the word replaced with the index of the word

Also, we will restrict the vocabulary to 50000 most common words. All other rare words will be replaced with `UNK`


In [11]:
import collections

vocab_size = 50000

def build_dataset(word_tokens):
    counts = [('UNK', -1)]
    counts.extend(collections.Counter(word_tokens).most_common(vocab_size - 1))
    
    dictionary = dict()
    reverse_dictionary = dict()
    idx = 0
    for word, _ in counts:
        dictionary[word] = idx
        reverse_dictionary[idx] = word
        idx += 1
    #TODO: See if we need UNK's count
    
    data = [dictionary[word if word in dictionary else 'UNK'] for word in word_tokens]
    
    assert(len(dictionary) == vocab_size)
    
    return counts, dictionary, reverse_dictionary, data
    
counts, dictionary, reverse_dictionary, data = build_dataset(content)
print('Top most common words in the corpus are', counts[0:5])
print('Sample data', data[0:10])

Top most common words in the corpus are [('UNK', -1), ('the', 226881), (',', 184013), ('.', 120944), ('of', 116323)]
Sample data [1721, 9, 8, 16471, 223, 4, 5165, 4456, 26, 11590]


We will now write the function that will generate batches of data for skipgram algorithm

We will have two vectors returned, one for target word and the context word which forms the label

In [12]:
data_index = 0
def generate_batch_skip_gram(batch_size, window_size):
    global data_index
    
    batch_target = []
    batch_context = []
    
    span = 2 * window_size + 1
    deque = collections.deque(maxlen = span)
    
    for _ in range(span):
        deque.append(data[data_index])
        data_index = (data_index + 1) % len(data)
    
    
    for i in range(batch_size // (2 * window_size)):
        batch_target.extend([deque[window_size]] * (window_size * 2))
        labels = [deque[j] for j in list(range(window_size)) + list(range(window_size + 1, 2 * window_size + 1))]
        batch_context.extend(labels)
        deque.append(data[data_index])
        data_index = (data_index + 1) % len(data)
            
    return np.array(batch_target), np.array(batch_context)

In [13]:
print('Initial 10 words in the data are ', [reverse_dictionary[i] for i in data[:10]])
print()
for w in [1, 2]:
    data_index = 0
    batch_target, batch_context = generate_batch_skip_gram(batch_size = 8, window_size = w)
    print('Batch target with window size:', w, ' is:', [reverse_dictionary[i] for i in batch_target])
    print('Batch context with window size:', w, ' is:', [reverse_dictionary[i] for i in batch_context])

Initial 10 words in the data are  ['propaganda', 'is', 'a', 'concerted', 'set', 'of', 'messages', 'aimed', 'at', 'influencing']

Batch target with window size: 1  is: ['is', 'is', 'a', 'a', 'concerted', 'concerted', 'set', 'set']
Batch context with window size: 1  is: ['propaganda', 'a', 'is', 'concerted', 'a', 'set', 'concerted', 'of']
Batch target with window size: 2  is: ['a', 'a', 'a', 'a', 'concerted', 'concerted', 'concerted', 'concerted']
Batch context with window size: 2  is: ['propaganda', 'is', 'concerted', 'set', 'is', 'a', 'set', 'of']


---

**Skip-gram**

We will now implement Skip-gram algorithm


In [14]:
import random 
import tensorflow as tf
import csv

batch_size = 128
embedding_dimension = 128
window_size = 4

#Words with lower index in are more frequent. 
#For example word with index 1 is more frequent than word with index 100
#Select 16 from first 50 common words and 16 from 1000th to 1050th common words
validation_words = random.sample(range(50), 16) + random.sample(range(1000, 1050), 16)


#Reset tf graph
tf.reset_default_graph()

#Input and labels placeholders
x = tf.placeholder(name = 'input', dtype = tf.int32, shape = [batch_size])
y = tf.placeholder(name = 'labels', dtype = tf.int32, shape = [batch_size, 1])


#Constant for validation_words
validation_set = tf.constant(validation_words, name = 'validation')


#Embeddings
embeddings = tf.Variable(
            tf.random_uniform(shape = [vocab_size, embedding_dimension], 
                              dtype = tf.float32,
                              minval = -1,
                              maxval = 1), name = 'embeddings')


#Softmax layer

softmax_weights = tf.Variable(
                        tf.truncated_normal(shape = [vocab_size, embedding_dimension],
                                            dtype = tf.float32, 
                                            stddev = 0.5 / math.sqrt(embedding_dimension) #See why?
                                           ), name = 'sm_weights')

softmax_bias = tf.Variable(
                        tf.random_uniform(shape = [vocab_size],
                                          dtype = tf.float32,
                                          minval = 0.0,
                                          maxval = 0.01), name = 'sm_weights')


Let us define the model

TODO:
For ``tf.nn.sampled_softmax_loss``, read [this](https://arxiv.org/abs/1412.2007)


In [15]:

#Lookup embeddings from input
embeds = tf.nn.embedding_lookup(embeddings, x)

loss = tf.reduce_mean(
            tf.nn.sampled_softmax_loss(
                weights = softmax_weights,
                biases = softmax_bias,
                labels = y,
                inputs = embeds,
                num_sampled = 32,   #Negative samples
                num_classes = vocab_size
            )
)


Similarity metrics on validation dataset

In [16]:
norm = tf.sqrt(tf.reduce_sum(tf.square(embeddings), 1, keep_dims=True))
normalized_embeddings = embeddings / norm
valid_embeddings = tf.nn.embedding_lookup(normalized_embeddings, validation_set)
similarity = tf.matmul(valid_embeddings, tf.transpose(normalized_embeddings))

Training operation

In [17]:
num_steps = 100002
skip_losses = []

optimizer = tf.train.AdagradOptimizer(1.0).minimize(loss)

with tf.Session() as session:
    tf.global_variables_initializer().run()
    cumulative_loss  = 0

    for step in range(1, num_steps):
        
        #1. Get batch
        batch_target, batch_context = generate_batch_skip_gram(
                                        batch_size = batch_size,
                                        window_size = window_size)
        
        feed_dict = {x : batch_target, y : batch_context.reshape(-1, 1)}
        _, l = session.run([optimizer, loss], feed_dict=feed_dict)
        
        cumulative_loss += l
        
        if step % 2000 == 0:
            mean_loss = cumulative_loss / 2000
            print('Average loss at step', step, 'is ', mean_loss)
            skip_losses.append(mean_loss)
            cumulative_loss = 0
            
        if step % 10000 == 0:
            print('='*50)
            print('='*7, 'Validating against validation set', '='*7)
            print('='*100)
            sim = session.run(similarity)
            for idx, validation_word in enumerate(validation_words):
                v_word = reverse_dictionary[validation_word]
                sim_vector = (-sim[idx, :]).argsort()[1:6] #Top 5
                sim_words = [reverse_dictionary[i] for i in sim_vector]
                print('Nearest 5 words to', v_word, ' are', sim_words)
        
    skip_gram_final_embeddings = normalized_embeddings.eval()        
    
np.save('skip_embeddings',skip_gram_final_embeddings)

with open('skip_losses.csv', 'wt') as f:
    writer = csv.writer(f, delimiter=',')
    writer.writerow(skip_losses)


Average loss at step 2000 is  3.99514165151
Average loss at step 4000 is  3.62323148227
Average loss at step 6000 is  3.58598815215
Average loss at step 8000 is  3.5107331692
Average loss at step 10000 is  3.4975050782
======= Validating against validation set =======
Nearest 5 words to its  are ['surpassed', 'ugarte', 'greatly', 'isotope', 'foxes']
Nearest 5 words to or  are ['euclid', 'egyptians', 'bibliographies', 'rays', 'exponentially']
Nearest 5 words to to  are ['in', 'gameplay', ',', 'adopt', 'that']
Nearest 5 words to the  are [',', 'in', 'a', '.', 'and']
Nearest 5 words to on  are [',', 'in', 'with', 'scialfa', 'ave.']
Nearest 5 words to ;  are ['churchyard', 'tub', '5,748', 'sung', 'preparatory']
Nearest 5 words to his  are ['dusk', 'albertosaurus', 'governorship', 'i-696', 'sin']
Nearest 5 words to not  are ['modeled', 'boycott', 'radical', 'spencer', 'enhancer']
Nearest 5 words to city  are ['mitoxantrone', 'penn', 'filippo', '1855.', 'outings']
Nearest 5 words to most  ar

Average loss at step 32000 is  3.37155949414
Average loss at step 34000 is  3.3447720592
Average loss at step 36000 is  3.33436882722
Average loss at step 38000 is  3.34803752995
Average loss at step 40000 is  3.33136819696
======= Validating against validation set =======
Nearest 5 words to its  are ['the', "'s", 'a', 'an', 'their']
Nearest 5 words to or  are ['caldera', "'", 'uninterested', 'called', 'fasteners']
Nearest 5 words to to  are ['for', 'would', 'disdain', 'flat-topped', 'uncorrupted']
Nearest 5 words to the  are [',', 'a', 'and', 'of', 'in']
Nearest 5 words to on  are ['in', ',', 'damrak', 'fundamentalism', '1899']
Nearest 5 words to ;  are ['.', '.in', 'boxcars', 'inhg', ':']
Nearest 5 words to his  are ['her', "'s", 'cochran', 'their', 'interred']
Nearest 5 words to not  are ['it', 'this', 'they', 'anahuac', 'that']
Nearest 5 words to city  are ['kolb', 'world', 'middle', 'largest', 'flyer']
Nearest 5 words to most  are ['other', 'seizing', 'motility', '70,000.', 'kenti

Average loss at step 62000 is  3.29944757771
Average loss at step 64000 is  3.31188670385
Average loss at step 66000 is  3.26520181715
Average loss at step 68000 is  3.2787614634
Average loss at step 70000 is  3.29066977203
======= Validating against validation set =======
Nearest 5 words to its  are ['demyelinating', 'composition', 'idiom', 'his', 'their']
Nearest 5 words to or  are ['any', 'diagnostic', 'non-alignment', 'dictating', 'suited']
Nearest 5 words to to  are ['would', 'that', 'could', 'can', 'will']
Nearest 5 words to the  are ['a', 'and', ',', 'this', "'s"]
Nearest 5 words to on  are ['upon', 'from', 'at', 'banaba', 'kraus']
Nearest 5 words to ;  are ['.', ':', ',', 'drinkers', '``']
Nearest 5 words to his  are ['her', 'their', "'s", 'he', 'this']
Nearest 5 words to not  are ['if', 'it', 'so', 'they', 'whether']
Nearest 5 words to city  are ['area', 'west', 'kolb', "''bounty", 'ppd']
Nearest 5 words to most  are ['one', 'more', 'still', 'many', 'lacklustre']
Nearest 5 wor

Average loss at step 92000 is  3.29356581634
Average loss at step 94000 is  3.25562360454
Average loss at step 96000 is  3.28348783398
Average loss at step 98000 is  3.27867464328
Average loss at step 100000 is  3.26950659144
======= Validating against validation set =======
Nearest 5 words to its  are ['their', 'his', 'an', 'gif', 'kat']
Nearest 5 words to or  are ['peniamina', 'magnify', 'interface', 'revulsion', 'like']
Nearest 5 words to to  are ['would', 'will', ',', 'that', 'and']
Nearest 5 words to the  are ['a', ',', "'s", '.', 'and']
Nearest 5 words to on  are ['in', 'upon', 'from', ',', '21']
Nearest 5 words to ;  are [':', '.', 'but', '(', ',']
Nearest 5 words to his  are ['her', 'their', 'he', 'its', "'s"]
Nearest 5 words to not  are ['that', 'so', 'it', 'if', 'but']
Nearest 5 words to city  are ['area', 'largest', 'town', 'drachma', 'besra']
Nearest 5 words to most  are ['classifies', 'one', 'category', 'first', 'still']
Nearest 5 words to were  are ['are', 'had', 'was', '


---

#### Visualizing the words

The visualization using TSNE doesn't work on my OSX machine and complains about infinite/NaN values in embeddings though there are none

---

##### Implement CBOW

TODO: Take up this part later similar to Skipgram